# -*- coding: utf-8 -*-
"""와인품질 분류대회 EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c_OguI3J0sQexpqY9DJjaXJk4pqWpVuh

#와인 품질 분류대회 EDA
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import patches
# %matplotlib inline


train = pd.read_csv('train.csv')
train.head()





